# Generated by Django 2.2.3 on 2019-07-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customerfamily',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
