# Generated by Django 2.2.3 on 2019-07-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190707_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfamily',
            name='relation',
            field=models.CharField(choices=[('Sister', 'Sister'), ('Brother', 'Brother'), ('Father', 'Father'), ('Mother', 'Mother')], default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerfamily',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='customer.Customer'),
        ),
    ]
